# Generated by Django 5.0 on 2023-12-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.JSONField()),
                ('size_m2', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['deleted_at'], name='citadel_pro_deleted_e7de21_idx')],
            },
        ),
    ]
