# Generated by Django 5.0 on 2023-12-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citadel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
