# Generated by Django 5.0 on 2023-12-25 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citadel', '0002_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['deleted_at'], name='citadel_pro_deleted_e7de21_idx'),
        ),
    ]
