# Generated by Django 5.0 on 2023-12-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citadel', '9999_demo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
